version: '3.8'

services:
  #데이터베이스
  # 레디스 (장바구니 서비스용)
  # 레디스 (장바구니 서비스용)
  localy-cart-redis: # 레디스 서비스 이름
    image: redis:latest
    hostname: localy-cart-redis
    ports:
      - "6379:6379" # <-- 이 라인을 추가합니다! 로컬 6379 포트와 컨테이너 내부 6379 포트 연결
    restart: unless-stopped
  localy-order-postgre:
    image: postgres:latest
    hostname: localy-order-postgre
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: orderuser # 이전 대화에서 사용한 사용자 이름
      POSTGRES_PASSWORD: orderpass # 이전 대화에서 사용한 비밀번호
    volumes:
      - order_data:/var/lib/postgresql/data
    restart: unless-stopped

  localy-payment-postgre:
    image: postgres:latest
    hostname: localy-payment-postgre
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: paymentdb
      POSTGRES_USER: paymentuser # 이전 대화에서 사용한 사용자 이름
      POSTGRES_PASSWORD: paymentpass # 이전 대화에서 사용한 비밀번호
    volumes:
      - payment_data:/var/lib/postgresql/data
    restart: unless-stopped

  localy-pgadmin:
    image: dpage/pgadmin4:latest
    hostname: localy-pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    depends_on:
      - localy-order-postgre
      - localy-payment-postgre
    restart: unless-stopped

# 데이터 지속성을 위한 볼륨 정의 (DB 데이터 보존)
volumes:
  order_data:
  payment_data:
  # redis_data: # 레디스 데이터도 보존하려면 추가