server:
  port: 9001
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: user-service
  lifecycle:
    timeout-per-shutdown-phase: 15s

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: user-service
            client-secret: user-secret
            authorization-grant-type: client_credentials
            scope:
              - openid
              - profile
              - email
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/localy
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/localy