server:
  port: 9001
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: user-service
  lifecycle:
    timeout-per-shutdown-phase: 15s

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: user-service
            client-secret: user-secret
            authorization-grant-type: client_credentials
            scope:
              - openid
              - profile
              - email
        provider:
          keycloak:
            # 환경 변수 사용, 기본값으로 localhost 설정
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/localy}
      resource-server:
        jwt:
          # 환경 변수 사용, 기본값으로 localhost 설정
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/localy}

# WebClientConfig에서 사용할 Keycloak 기본 URL 환경 변수 설정
# 이 환경 변수도 기본값으로 localhost를 사용합니다.
keycloak:
  base-url: ${KEYCLOAK_BASE_URL:http://localhost:8080/realms/localy}
    