server:
  port: 8091 # Docker Compose에서 8092:8092로 매핑됨

spring:
  application:
    name: order-service # 서비스 이름 지정

  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb # DB 서비스 이름, 기본 포트, DB 이름
    username: orderuser # Docker Compose env에 설정한 사용자
    password: orderpass # Docker Compose env에 설정한 비밀번호
    driver-class-name: org.postgresql.Driver

  jpa: # JPA 설정 예시
    hibernate:
      ddl-auto: update # 테스트용. 운영 시에는 migrate 도구 사용 권장
    show-sql: true # 개발/테스트 시 유용
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092 # Docker Compose의 카프카 서비스 이름과 내부 통신용 포트

  cloud:
    stream:
      kafka:
        binder:
          brokers: ${spring.kafka.bootstrap-servers} # 카프카 바인더도 동일한 주소 사용
          # properties:
          #   configuration:
          #     # 컨슈머 및 프로듀서 공통 속성
      bindings:
        # '주문 생성 이벤트' 발행을 위한 Output Binding (StreamBridge 또는 Supplier 빈 이름과 매핑)
        # 예: StreamBridge를 사용한다면 streamBridge.send("orderCreatedEvent-out-0", event)
        orderCreatedProducer-out-0:
          destination: order-created # 발행할 카프카 토픽 이름 (결제 서비스의 Input destination과 일치해야 함)
          contentType: application/json # 메시지 컨텐츠 타입 (직렬화 방식과 일치)
        # '결제 결과 이벤트' 소비를 위한 Input Binding (Consumer 빈 이름과 매핑)
        # 예: @Bean Consumer<PaymentResultEvent> paymentResultEventConsumer()
        paymentResultConsumer-in-0: # 새로운 입력 바인딩
          destination: payment-result # 소비할 카프카 토픽 이름 (결제 서비스의 Output destination과 일치해야 함)
          group: order-payment-result-group # 이 컨슈머가 속할 컨슈머 그룹 이름 (동일 토픽을 여러 서비스가 소비 시 그룹 이름은 각 서비스별로 달라야 함)
          # kafka.consumer.properties: # 추가 Kafka 컨슈머 속성
          #   auto.offset.reset: earliest # 또는 latest (오프셋이 없을 때 시작 위치)
          consumer:
            configuration:
              auto.offset.reset: earliest
              key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
              value.deserializer: org.springframework.kafka.support.serializer.JsonSerializer
              spring.json.trusted.packages: com.localy.payment_service.payment.message.dto # OrderCreatedEvent 패키지 경로 추가
    function:
      definition: orderCreatedProducer;paymentResultConsumer